# View examples and documentation at https://deliverybot.dev/docs/
production:
  environment: PRODUCTION
  production_environment: true
  required_contexts: ['deployment']

staging:
  environment: STAGING
  production_environment: false

integration:
  environment: INTEGRATION
  production_environment: true
  auto_deploy_on: pr
  required_contexts: []
