name: ci

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Bump minor version 2
      if: github.ref == 'refs/heads/master'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin master
        npm version minor
        git push origin HEAD:master
        
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: andrii-grebenkov/testTask
        event-type: my-event

    - name: Bump patch version
      if: contains(github.ref, 'patch')
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm version patch
        git push origin HEAD --tags
        
  everyTime:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Bump minor version
      if: github.ref == 'refs/heads/master'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
