name: trigger

on:
  push:
    branches: 
    - master
    - main
    - r*

jobs:   
  everyTimeTrigger:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Bump minor version
      if: github.ref == 'refs/heads/master'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
